apps/locals/urls.py
# Django
from django.urls import path
# Apps
from . import views

app_name = "locals_app"

urlpatterns = [
    path('', views.SearchView.as_view(), name='user-search'),
    path('dni/<str:dni>', views.UserView.as_view(), name='user'),

    path('panel/<str:local>', views.PanelView.as_view(), name='panel'),
    path('<str:local>/gerente/agregar', views.ManagerCreateView.as_view(), name='manager-add'),
    path('<str:local>/gerente/<pk>/', views.ManagerUpdateView.as_view(), name='manager-update'),
    path('gerente/eliminar/<str:local>/<pk>/', views.ManagerDeleteView.as_view(), name='manager-delete'),

    path('<str:local>/empleado/agregar', views.EmployeeCreateView.as_view(), name='employee-add'),
    path('<str:local>/empleado/<pk>/', views.EmployeeUpdateView.as_view(), name='employee-update'),
    path('empleado/eliminar/<str:local>/<pk>/', views.EmployeeDeleteView.as_view(), name='employee-delete'),

    path('renovate/<str:local>/<int:pk>/<int:days>', views.RenovateView.as_view(), name='renovate'),
]

personal/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    # users app
    re_path('', include('apps.users.urls')),
    re_path('', include('apps.locals.urls')),
    re_path('', include('apps.sales.urls')),
    re_path(r'^kuai/(.*)$', TemplateView.as_view(template_name='index.html')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/locals/models.py
# Django
from django.db import models
from django.conf import settings
from django.utils.safestring import mark_safe
from django.utils.text import slugify
from django.utils import timezone
from datetime import date
from dateutil.relativedelta import relativedelta


class Local(models.Model):
    logo = models.ImageField('logo', upload_to='media/local', blank=True, null=True)
    name = models.CharField('Nombre', max_length=100)
    slug = models.SlugField(max_length=100, unique=True, null=True, blank=True)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='Dueño')
    phone = models.CharField('Telefono', max_length=100, help_text="809-472-2626", blank=True)

    class Meta:
        verbose_name = 'Local'
        verbose_name_plural = 'Locales'

    def __str__(self):
        return "{}".format(self.name)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Local, self).save(*args, **kwargs)

    def admin_thumbnail(self):
        return mark_safe('<img src="/%s" width="140" />' % self.logo)
    admin_thumbnail.short_description = 'Thumbnail'
    admin_thumbnail.allow_tags = True


class Manager(models.Model):
    local = models.ForeignKey(Local, on_delete=models.CASCADE, verbose_name='Local')
    manager = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='Gerente', related_name='manager'
    )

    class Meta:
        verbose_name = 'Gerente'
        verbose_name_plural = 'Gerentes'

    def __str__(self):
        return "{}".format(self.manager.get_full_name())


class Employee(models.Model):
    local = models.ForeignKey(Local, on_delete=models.CASCADE, verbose_name='Local')
    employee = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='Empleado', related_name='employee'
    )
    due_date = models.DateField(verbose_name='Fecha de vencimiento', default=timezone.now)

    class Meta:
        verbose_name = 'Empleado'
        verbose_name_plural = 'Empleados'

    def save(self, *args, **kwargs):
        if not self.id:
            self.due_date = date.today() + relativedelta(months=1)
        return super(Employee, self).save(*args, **kwargs)

    def __str__(self):
        return "{}".format(self.employee.get_full_name())

apps/locals/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import (View, )
from django.shortcuts import render, redirect
from django.contrib import messages

# apps
from apps.locals.models import Local, Manager
from apps.locals.forms import ManagerForm, EmployeeForm, ManagerUpdateForm, EmployeeUpdateForm
from apps.users.models import User
from apps.locals.models import Employee

# other
from dateutil.relativedelta import relativedelta
import datetime
# from datetime import date


# Function
def local_(user):
    if user.type_user == '1':
        return Local.objects.filter(owner=user)
    elif user.type_user == '2':
        return Local.objects.filter(manager__manager=user)


def is_your_local(user, local):
    if user.type_user == '1':
        exist = Local.objects.filter(name=local, owner=user).exists()
    elif user.type_user == '2':
        exist = Local.objects.filter(name=local, manager__manager=user).exists()
    return exist


def card(dni):
    context = {}
    try:
        user = User.objects.get(dni=dni)
        context['valid'] = False

        a = datetime.date.today()
        # a = datetime.datetime(2022, 4, 1)

        if user.type_user == '3':
            for x in user.employee.all():
                if x.due_date.strftime("%Y-%m-%d") >= a.strftime("%Y-%m-%d"):
                    context['valid'] = True
        else:
            context['valid'] = True

        context['user_search'] = user
        context['exist'] = True
    except Exception as e:
        print(e)
        context['exist'] = False
    return context


# views
class SearchView(View):
    def get(self, request, *args, **kargs):
        context = {}
        search = request.GET.get('search')
        if(search and len(search) > 0):
            context = card(search)
        return render(request, 'users/entry.html', context)


class UserView(View):
    def get(self, request, dni, *args, **kwargs):
        return render(request, 'user.html', card(dni))


class PanelView(LoginRequiredMixin, View):
    def get(self, request, local, *args, **kwargs):
        local = Local.objects.get(slug=local)
        if not is_your_local(request.user, local):
            return redirect('users_app:user-login')

        # a = datetime.date.today() + relativedelta(day=31)
        # b = datetime.date.today()
        # # a = datetime.datetime(2022, 3, 29) + relativedelta(day=31)
        # # b = datetime.datetime(2022, 3, 29)
        # c = a - b
        # if c.days < 3:
        #     renovate = True
        # else:
        #     renovate = False
        return render(request, 'locals/list.html', {
            'locals': local_(self.request.user),
            'local': local,
            # 'renovate': renovate,
        })


# Manager
class ManagerCreateView(View):
    def get(self, request, local, *args, **kwargs):
        return render(request, 'locals/manager/add_manager.html', {
            'form': ManagerForm(),
            'local': Local.objects.get(slug=local),
            'locals': local_(request.user),
            'manager': True,
        })

    def post(self, request, local, *args, **kwargs):
        form = ManagerForm(request.POST, request.FILES)

        if form.is_valid():
            form.save(local=local, type_user=2)
            messages.add_message(request, messages.SUCCESS, 'Gerente creado')
            return redirect('locals_app:panel', local=local)
        return render(request, 'locals/manager/add_manager.html', {
            'form': form,
            'local': Local.objects.get(slug=local),
            'locals': local_(request.user),
            'manager': True,
        })


class ManagerUpdateView(View):
    def get(self, request, local, pk, *args, **kwargs):
        return render(request, 'locals/manager/update_manager.html', {
            'form': ManagerUpdateForm(instance=User.objects.get(pk=pk)),
            'local': Local.objects.get(slug=local),
            'locals': local_(request.user),
            'manager': True,
        })

    def post(self, request, local, pk, *args, **kwargs):
        form = ManagerUpdateForm(request.POST, request.FILES, instance=User.objects.get(pk=pk))
        if form.is_valid():
            form._save()
            # print(form.cleaned_data)
            messages.add_message(request, messages.SUCCESS, 'Gerente editado')
            return redirect('locals_app:panel', local=local)
        return render(request, 'locals/manager/add_manager.html', {
            'form': form,
            'local': Local.objects.get(slug=local),
            'locals': local_(request.user),
            'manager': True,
        })


class ManagerDeleteView(LoginRequiredMixin, View):
    def post(self, request, local, pk, *args, **kwargs):
        Manager.objects.get(pk=pk).delete()
        messages.add_message(request, messages.SUCCESS, 'Gerente Eliminado')
        return redirect('locals_app:panel', local=local)


# Employe
class EmployeeCreateView(View):
    def get(self, request, local, *args, **kwargs):
        return render(request, 'locals/manager/add_manager.html', {
            'form': EmployeeForm(),
            'local': Local.objects.get(slug=local),
            'locals': local_(request.user),
        })

    def post(self, request, local, *args, **kwargs):
        form = EmployeeForm(request.POST, request.FILES)

        if form.is_valid():
            form.save(local=local, type_user=3)
            messages.add_message(request, messages.SUCCESS, 'Empleado creado')
            return redirect('locals_app:panel', local=local)
        return render(request, 'locals/manager/add_manager.html', {
            'form': form,
            'local': Local.objects.get(slug=local),
            'locals': local_(request.user),
        })


class EmployeeUpdateView(View):

    def get(self, request, local, pk, *args, **kwargs):
        return render(request, 'locals/manager/update_manager.html', {
            'form': EmployeeUpdateForm(instance=User.objects.get(pk=pk)),
            'local': Local.objects.get(slug=local),
            'locals': local_(request.user),
        })

    def post(self, request, local, pk, *args, **kwargs):
        form = EmployeeUpdateForm(request.POST, request.FILES, instance=User.objects.get(pk=pk))
        if form.is_valid():
            form.save()
            messages.add_message(request, messages.SUCCESS, 'Empleado editado')
            return redirect('locals_app:panel', local=local)
        return render(request, 'locals/manager/add_manager.html', {
            'form': form,
            'local': Local.objects.get(slug=local),
            'locals': local_(request.user),
        })


class EmployeeDeleteView(LoginRequiredMixin, View):
    def post(self, request, local, pk, *args, **kwargs):
        Employee.objects.get(pk=pk).delete()
        messages.add_message(request, messages.SUCCESS, 'Empleado Eliminado')
        return redirect('locals_app:panel', local=local)


# api
class RenovateView(LoginRequiredMixin, View):
    def get(self, request, local, pk, days, *args, **kwargs):
        e = Employee.objects.filter(pk=pk)
        # td = e[0].due_date + relativedelta(months=1)

        td = datetime.date.today() + relativedelta(months=1)
        # td = datetime.datetime(2022, 3, 28) + relativedelta(months=1)
        e.update(due_date=td)

        messages.add_message(request, messages.SUCCESS, 'Empleado Renovado')
        return redirect('locals_app:panel', local=local)

templates/locals/list.html
{% extends "base.html" %}

{% load static %}
{% load validate %}

{% block css %}
  <link type="text/css" rel="stylesheet" href=" {% static 'lightgallery/css/lightgallery.min.css' %}" />
  <style type="text/css">
    .vencido {
      color: rgba(249,49,84,1)!important;
    }
    .activo {
      color: rgba(0,183,74,1)!important;
    }
  </style>
{% endblock css %}

{% block content %}
<!--Section: Sales Performance KPIs-->
<section class="mb-4">
  <div class="card">
    <div class="card-header text-center py-3">
      <h5 class="mb-0 text-center">
        <strong>Panel {{ local.name }}</strong>
      </h5>
    </div>

    <div class="card-body">
      {% if messages %}
        {% for message in messages %}
          <div class="alert alert-dismissible fade show alert-success" role="alert" data-mdb-color="warning" id="customxD">
            {{ message }}
            <button type="button" class="btn-close" data-mdb-dismiss="alert" aria-label="Close"></button>
          </div>
        {% endfor %}
      {% endif %}

      <br>
      <h3>
        Gerentes 
        {% if user.type_user == '1' %}
          <a href="{% url 'locals_app:manager-add' local.slug  %}" class="btn btn-primary px-3">Agregar <i class="fa-solid fa-plus ms-2"></i></a>
        {% endif %}
      </h3>
      <div class="table-responsive">
        <table class="table table-hover text-nowrap">
          <thead>
            <tr>
              <td>Foto</td>
              <td>QR</td>
              <td>Dni</td>
              <td>Nombre completo</td>
              <td>Email</td>
              <td>Telefono</td>
              {% if user.type_user == '1' %}
                <td>Editar</td>
                <td>
                  Eliminar
                  <form id="delete_manager" action="" method="POST">
                    {% csrf_token %}
                  </form>
                </td>
                <td>
                  Compartir
                </td>
              {% endif %}
            </tr>
          </thead>
          <tbody>
            {% for m in local.manager_set.all %}
              <tr class="lightgallery">
                <td>
                  <a href="/{{ m.manager.image }}" data-lg-size="1600-2400" class="custom-selector">
                    <img src="/{{ m.manager.image }}" alt="" width="50">
                  </a>
                </td>
                <td>
                  <a href="/{{ m.manager.qr }}" data-lg-size="1024-800" class="custom-selector">
                    <img src="/{{ m.manager.qr }}" alt="" width="50">
                  </a>
                </td>
                <td>{{ m.manager.dni }}</td>
                <td>{{ m.manager.get_full_name }}</td>
                <td>{{ m.manager.email|default_if_none:"-" }}</td>
                <td>{{ m.manager.phone|default_if_none:"-" }}</td>
                {% if user.type_user == '1' %}
                <td><a class="btn btn-warning px-3" href="{% url 'locals_app:manager-update' local.slug m.manager.pk %} "><i class="fas fa-edit"></i></a></td>
                <td><button class="btn btn-danger px-3" onclick="DeleteManager('{% url "locals_app:manager-delete" local.slug m.pk %}', '#delete_manager')"><i class="fa-solid fa-trash"></i></button></td>
                <td><a href="https://api.whatsapp.com/send?text=https://personal.devotoshopping.com.ar/dni/{{m.manager.dni}}" target="_blank" class="btn btn-info px-3"><i class="fa-solid fa-share"></i></a></td>
                {% endif %}
              </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
      <br>
      <h3>Empleados <a href="{% url 'locals_app:employee-add' local.slug %}" class="btn btn-primary px-3">agregar <i class="fa-solid fa-plus ms-2"></i></a></h3>
      <div class="table-responsive">
        <table class="table table-hover text-nowrap">
          <thead>
            <tr>
              <td>Foto</td>
              <td>QR</td>
              <td>Dni</td>
              <td>Nombre completo</td>
              <td>Email</td>
              <td>Telefono</td>
              <td>Mes de Vencimiento</td>
              <td>Renovar</td>
              <td>Editar</td>
              <td>
                Eliminar
                <form id="delete_employee" action="" method="POST">
                  {% csrf_token %}
                </form>
              </td>
              <td>
                Compartir
              </td>
            </tr>
          </thead>
          <tbody>
            {% for e in local.employee_set.all %}
              <tr class="lightgallery">
                <td>
                  <a href="/{{ e.employee.image }}" data-lg-size="1600-2400" class="custom-selector">
                    <img src="/{{ e.employee.image }}" alt="" width="50">
                  </a>
                </td>
                <td>
                  <a href="/{{ e.employee.qr }}" data-lg-size="1024-800" class="custom-selector">
                    <img src="/{{ e.employee.qr }}" alt="" width="50">
                  </a>
                </td>

                <td>{{ e.employee.dni }}</td>
                <td>{{ e.employee.get_full_name }}</td>
                <td>{{ e.employee.email|default_if_none:"-" }}</td>
                <td>{{ e.employee.phone|default_if_none:"-" }}</td>
                <td><strong class="{% validate e.employee %}">{{ e.due_date|date:"F, Y" }}</strong></td>
                <td><a href="{% url 'locals_app:renovate' local.slug e.pk 2  %}" class="btn btn-success px-3"><i class="fa-solid fa-arrows-rotate"></i></a></td>
                <td><a class="btn btn-warning px-3" href="{% url 'locals_app:employee-update' local.slug e.employee.pk %} "><i class="fas fa-edit"></i></a></td>
                <td><button class="btn btn-danger px-3" onclick="DeleteManager('{% url "locals_app:employee-delete" local.slug e.pk %}', '#delete_employee')"><i class="fa-solid fa-trash"></i></button></td>
                <td><a href="https://api.whatsapp.com/send?text=https://personal.devotoshopping.com.ar/dni/{{e.employee.dni}}" target="_blank" class="btn btn-info px-3"><i class="fa-solid fa-share"></i></a></td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
</section>

{% endblock content %}

{% block js %}
  <script src="{% static 'lightgallery/js/lightgallery.min.js' %}"></script>
  <script>
    function DeleteManager(url, id){
      var result = confirm("Estas seguro?");
      if (result == true) {
        let delete_manager = document.querySelector(id)
        delete_manager.setAttribute('action', url)
        delete_manager.submit()
      }
    }
  </script>
  <script type="text/javascript">

    var lg = document.querySelectorAll('.lightgallery');
    for ( var i = 0; i < lg.length; i++ ) {
        lightGallery( lg[i], {
        selector: '.custom-selector'
      });
    }

</script>
{% endblock js %}