apps/locals/urls.py
# Django
from django.urls import path
# Apps
from . import views

app_name = "locals_app"

urlpatterns = [
    path('', views.SearchView.as_view(), name='user-search'),
    path('dni/<str:dni>', views.UserView.as_view(), name='user'),

    path('panel/<str:local>', views.PanelView.as_view(), name='panel'),
    path('<str:local>/gerente/agregar', views.ManagerCreateView.as_view(), name='manager-add'),
    path('<str:local>/gerente/<pk>/', views.ManagerUpdateView.as_view(), name='manager-update'),
    path('gerente/eliminar/<str:local>/<pk>/', views.ManagerDeleteView.as_view(), name='manager-delete'),

    path('<str:local>/empleado/agregar', views.EmployeeCreateView.as_view(), name='employee-add'),
    path('<str:local>/empleado/<pk>/', views.EmployeeUpdateView.as_view(), name='employee-update'),
    path('empleado/eliminar/<str:local>/<pk>/', views.EmployeeDeleteView.as_view(), name='employee-delete'),

    path('renovate/<str:local>/<int:pk>/<int:days>', views.RenovateView.as_view(), name='renovate'),
]

apps/users/urls.py
# Django
from django.urls import path
# Apps
from . import views

app_name = "users_app"

urlpatterns = [
    path('login', views.LoginUser.as_view(), name='user-login'),
    path('logout', views.LogoutView.as_view(), name='user-logout'),
    path('panel', views.PanelView.as_view(), name='panel'),
]

personal/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    # users app
    re_path('', include('apps.users.urls')),
    re_path('', include('apps.locals.urls')),
    re_path('', include('apps.sales.urls')),
    re_path(r'^kuai/(.*)$', TemplateView.as_view(template_name='index.html')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/users/models.py
# Django
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from django.db import models
from django.utils.safestring import mark_safe

# Apps
from apps.users.managers import UserManager
from apps.locals.models import Local

# Other
import qrcode
from PIL import Image, ImageDraw
from io import BytesIO
from django.core.files import File


class User(AbstractBaseUser, PermissionsMixin):

    TYPE_USER = [
        ('1', 'Dueño'),
        ('2', 'Gerente'),
        ('3', 'Staff'),
    ]

    dni = models.IntegerField(unique=True)
    email = models.EmailField(blank=True, null=True)
    type_user = models.CharField("Tipo de Usuario", max_length=1, choices=TYPE_USER, default='3')
    first_name = models.CharField('Nombres', max_length=100)
    last_name = models.CharField('Apellidos', max_length=100)
    phone = models.CharField('Telefono', max_length=100, help_text="809-472-2626", blank=True, null=True)
    image = models.ImageField('foto', upload_to='media/user/employees', blank=True, null=True)
    qr = models.ImageField(upload_to='media/user/qrcode', blank=True)

    #
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)

    USERNAME_FIELD = 'dni'

    REQUIRED_FIELDS = [
        'first_name', 'last_name', 'type_user'
    ]

    objects = UserManager()

    class Meta:
        verbose_name = 'Usuario'
        verbose_name_plural = 'Usuarios'

    def get_short_name(self):
        return self.first_name

    def get_full_name(self):
        return "{} {}".format(self.first_name, self.last_name)

    def qr_thumbnail(self):
        if self.qr:
            return mark_safe('<img src="/%s" width="140" />' % self.qr)
        return '-'

    def locals(self):
        if self.is_superuser:
            return Local.objects.all()
        else:
            if self.type_user == '1':
                return Local.objects.filter(owner=self)
            elif self.type_user == '2':
                return Local.objects.filter(manager__manager=self)

    qr_thumbnail.short_description = 'Qr'
    qr_thumbnail.allow_tags = True

    def __str__(self):
        return self.get_full_name()

    def save(self, *args, **kwargs):
        # url = 'http://personal.devotoshopping.com.ar/dni/{}'.format(self.dni)
        url = self.dni
        qrcode_img = qrcode.make(url)
        canvas = Image.new("RGB", (300, 300), "white")
        ImageDraw.Draw(canvas)
        canvas.paste(qrcode_img)
        buffer = BytesIO()
        canvas.save(buffer, "PNG")
        self.qr.save('qr.png', File(buffer), save=False)
        canvas.close()
        return super(User, self).save(*args, **kwargs)

apps/users/forms.py
from django import forms
from django.contrib.auth import authenticate
# Apps
# from .models import User


class LoginForm(forms.Form):
    dni = forms.CharField(
        label='E-mail',
        required=True,
        widget=forms.NumberInput(
            attrs={
                'id': 'form1Example1',
                'class': 'form-control',
            }
        )
    )
    password = forms.CharField(
        label='Contraseña',
        required=True,
        widget=forms.PasswordInput(
            attrs={
                'id': 'form1Example2',
                'class': 'form-control',
            }
        )
    )

    def clean(self):
        dni = self.cleaned_data['dni']
        password = self.cleaned_data['password']

        if not authenticate(dni=dni, password=password):
            raise forms.ValidationError(
                'Los datos de usuario no son correctos'
            )

        return self.cleaned_data

apps/users/views.py
# Django
# from ast import Try
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect
from django.views.generic.edit import (
    FormView
)
from django.contrib.auth.mixins import LoginRequiredMixin
# from django.shortcuts import render
from django.views.generic import (View)

# Apps
# from apps.users.models import User
from apps.locals.models import Local
from .forms import (
    LoginForm,
)
import datetime


class LoginUser(FormView):
    template_name = 'users/login.html'
    form_class = LoginForm

    def get_success_url(self):
        if self.request.user.is_superuser:
            return reverse_lazy('sales_app:panel_su')
        else:
            # if self.request.user.type_user == '1':
            #     ls = Local.objects.filter(owner=self.request.user)
            # elif self.request.user.type_user == '2':
            #     ls = Local.objects.filter(manager__manager=self.request.user)
            return reverse_lazy('users_app:panel')

    def form_valid(self, form):
        user = authenticate(
            dni=form.cleaned_data['dni'],
            password=form.cleaned_data['password']
        )
        login(self.request, user)
        return super(LoginUser, self).form_valid(form)


class LogoutView(View):
    def get(self, request, *args, **kargs):
        logout(request)
        return HttpResponseRedirect(
            reverse(
                'users_app:user-login'
            )
        )


class PanelView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        if self.request.user.type_user == '1':
            ls = Local.objects.filter(owner=request.user)
        elif request.user.type_user == '2':
            ls = Local.objects.filter(manager__manager=request.user)

        return render(request, 'users/panel.html', {
            'locals': ls,
            'today': datetime.datetime.today()
        })

templates/base.html
{% load  static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta http-equiv="x-ua-compatible" content="ie=edge" />
    <title>{% block title %}{% endblock title %}</title>
    <!-- MDB icon -->
    <link rel="icon" href="img/mdb-favicon.ico" type="image/x-icon" />
    <!-- Font Awesome -->
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"
    />
    <!-- Google Fonts Roboto -->
    <link
      rel="stylesheet"
      href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700;900&display=swap"
    />
    <!-- MDB -->
    <link rel="stylesheet" href="{% static 'css/mdb.min.css' %}" />
    {% block css %}{% endblock css %}
    <style>
      body {
        background-color: #fbfbfb;
      }
      .main-header{
        width: 100%;
        height:50px;
        display: flex;
        align-items: center;
      }
      .logout {
        position: absolute;
        right: 0;
        top: 0;
        cursor: pointer;
        transform: translateX(-80%) translateY(50%);
      }
      .logout ul {
        padding-left: 0;
        list-style: none;
        margin-bottom: 0;
      }
      nav{
        position: absolute;
        left:-100%;
        top:0;
        width: 200px;
        top:50px;
        height:calc(100vh - 50px);
        background:#79B7BE;
        transition:.4s ease;
        z-index: 1;
      }
      .navigation {
        width: 100%;
        padding-left: 0;
      }
      .navigation li{
        list-style:none;
        width: 100%;
        border-bottom: 1px solid rgba(255,255,255,.5);
      }
      .navigation a{
        color:var(--main-color);
        display: block;
        line-height:3.5;
        padding: 0 10px;
        text-decoration:none;
        transition:.4s ease;
      }
      #btn-nav{
        display: none;
      }
      #btn-nav:checked ~ nav{
        left: 0%;
      }
      .btn-nav{
        color:var(--main-color);
        font-size:30px;
        position: absolute;
        left:0;
        top:0;
        cursor:pointer;
        padding:6.5px 15px;
        transition:.2s ease;
      }
      .list-group-item {
        background-color: #79B7BE;
        border-color: transparent;
      }
      .list-group-item span,
      .list-group-item i {
        color: #fff;
      }
      .list-group-item.active {
        background-color: #007A82;
        border-color: transparent;
      }
      .logo-nav {
        position: absolute;
        left: 0;
        top: 0;
        cursor: pointer;
        transform: translateX(80%) translateY(50%);
      }
      .enlace-logout {
        color: #202020;
        transition: all .3s;
      }
      .enlace-logout:hover {
        color: #007780;
      }
    </style>
  </head>
  <body class="body">
    <!-- Start your project here-->
    <div class="">
      <!--Main Navigation-->
      <header class="main-header">
        <div>
          <label for="btn-nav" class="btn-nav">
            <i class="fas fa-bars"></i>
          </label>
          <div class="logo-nav">
            <a class="" href="#">
              <img
                  style="height: 30px;"
                  src="{% static 'images/Devoto Logo-03.png' %}"
                  alt=""
                  loading="lazy"
              />
            </a>
          </div>
        </div>
        <div class="logout">
          <ul>
            <!-- Notification dropdown -->
            <!-- Avatar -->
            <li>
              <a class="enlace-logout" href="{% url 'users_app:user-logout' %}">
                Logout
              </a>
            </li>
          </ul>
        </div>
        <input type="checkbox" id="btn-nav">
        <nav class="nav">
          <ul class="navigation">
            {% for l in locals %}
              <li>
                <a
                  href="{% url 'locals_app:panel' l.slug %}"
                  class="list-group-item list-group-item-action py-2 ripple {% if l.slug == local.slug %}active{% endif %}"
                  aria-current="true"
                >
                  <i class="fas fa-tachometer-alt fa-fw me-3"></i
                    ><span>{{ l.name }}</span>
                </a>
              </li>
            {% endfor %}
          </ul>
        </nav>
      </header>
      <!--Main Navigation-->

      <!--Main layout-->
      <main style="margin-top: 58px">
        <div class="container pt-4">
          {% block content %}{% endblock content %}
          <!--Section: Sales Performance KPIs-->
        </div>
      </main>
      <!--Main layout-->
     </div>
    <!-- MDB -->
    <script src="https://code.jquery.com/jquery-1.11.0.min.js"></script>
    <script src="https://code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
    <script type="text/javascript" src=" {% static 'js/mdb.min.js' %}"></script>
    <!-- Custom scripts -->
    {% block js %}{% endblock js %}
  </body>
</html>

templates/user.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Font Awesome -->
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"
    />
    <!-- Google Fonts Roboto -->
    <link
      rel="stylesheet"
      href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700;900&display=swap"
    />
    <!-- MDB -->
    <title>Profile Card</title>
    <style>
      * {
        margin: 0;
        padding: 0;
        box-sizing: border-box;
        text-decoration: none;
        transition: 0.3s;
      }

      body {
        font-family: "Montserrat";
        background-color: #b8b6b6;
        color: #fdfdfd;
      }

      .card {
        max-width: 350px;
        margin: 150px auto 0;
        background-color: #42515a;
        box-shadow: 0 10px 90px #00000024;
        text-align: center;
        font-size: 20px;
        border-radius: 15px;
        margin-bottom: 15px;
      }

      .card .card-header {
        position: relative;
        height: 48px;
      }

      .card .card-header .profile-img {
        width: 130px;
        height: 130px;
        border-radius: 1000px;
        position: absolute;
        left: 50%;
        transform: translate(-50%, -50%);
        box-shadow: 0 0 20px #00000033;
        background: #fff;
      }

      .card .card-header.vencido .profile-img {
        border: 8px solid rgba(249,49,84,1)!important;
      }
      .card .card-header.activo .profile-img {
        border: 8px solid rgba(0,183,74,1)!important;
      }

      .card .card-body {
        padding: 35px 40px;
      }

      .card .card-body .name {
        margin-top: 10px;
        font-size: 22px;
        font-weight: bold;
      }

      .card .card-body .mail {
        font-size: 14px;
        color: #c2bdbd;
      }

      .card .card-body .job {
        margin-top: 10px;
        font-size: 14px;
      }
      .card .card-body .job a{
        color: #fff;
      }

      .card .social-links {
        display: flex;
        justify-content: center;
        align-items: center;
        margin-top: 30px;
        flex-direction: column;
      }

      .card .social-links .social-icon {
        display: inline-flex;
        align-items: center;
        justify-content: center;
        height: 40px;
        width: 40px;
        background-color: #c74385;
        color: #ffffff;
        font-size: 20px;
        border-radius: 100%;
        text-decoration: none;
        margin: 0 13px 30px 0;
      }

      .card .social-links .social-icon:last-child {
        margin-right: 0;
      }

      .card .card-footer {
        border-bottom-left-radius: 15px;
        border-bottom-right-radius: 15px;
        padding: 20px 0 20px 0;
      }
      .card .card-footer.vencido {
        background-color: rgba(249,49,84,1)!important;
      }
      .card .card-footer.activo {
        background-color: rgba(0,183,74,1)!important;
      }

      .card .card-footer .count {
        font-size: 14px;
      }

      @media screen and (max-width: 575px) {
        .card {
          width: 96%;
        }

        .card .card-body {
          padding: 10px 20px;
        }
      }
    </style>
</head>
<body>
  {% if exist %}
    <div class="card">
      <div class="card-header {% if valid %}activo{% else %}vencido{% endif %}">
        <img src="{{ user_search.image.url }}" alt="Profile Image" class="profile-img">
      </div>
      <div class="card-body">
        <div>
          <img src="{{ user_search.qr.url }}" alt="qr" style='width: 50%;'>
        </div>
        <p class="name">{{ user_search.get_full_name }}</p>
        <p>{{ user_search.get_type_user_display }}</p>
        <p>{{ user_search.dni }}</p>

        {% if user_search.phone %}
          <p class="job"><a href="tel:{{ user_search.phone }}">{{ user_search.phone }}</a></p>
        {% endif %}

        <div class="social-links">
          <h3>Local</h3>
          <div>
            {% if user.type_user == '2' %}
              {% for e in user_search.manager.all %}
                <img src="{{ e.local.logo.url }}" alt="Profile Image" class="profile-img" width='50'>
              {% endfor %}
            {% elif user.type_user == '3' %}
              {% for e in user_search.employee.all %}
                <img src="{{ e.local.logo.url }}" alt="Profile Image" class="profile-img" width='50'>
              {% endfor %}
            {% endif %}
          </div>
        </div>
      </div>

      <div class="card-footer {% if valid %}activo{% else %}vencido{% endif %}">
        {% if valid %}
          <p class="count">Activo</p>
        {% else %}
          <p class="count">Vencido</p>
        {% endif %}
      </div>
    </div>
  {% else %}
    <h1 style="text-align: center;">El usuario no existe</h1>
  {% endif %}
</body>
</html>