apps/locals/urls.py
# Django
from django.urls import path
# Apps
from . import views

app_name = "locals_app"

urlpatterns = [
    path('', views.SearchView.as_view(), name='user-search'),
    path('dni/<str:dni>', views.UserView.as_view(), name='user'),

    path('panel/<str:local>', views.PanelView.as_view(), name='panel'),
    path('<str:local>/gerente/agregar', views.ManagerCreateView.as_view(), name='manager-add'),
    path('<str:local>/gerente/<pk>/', views.ManagerUpdateView.as_view(), name='manager-update'),
    path('gerente/eliminar/<str:local>/<pk>/', views.ManagerDeleteView.as_view(), name='manager-delete'),

    path('<str:local>/empleado/agregar', views.EmployeeCreateView.as_view(), name='employee-add'),
    path('<str:local>/empleado/<pk>/', views.EmployeeUpdateView.as_view(), name='employee-update'),
    path('empleado/eliminar/<str:local>/<pk>/', views.EmployeeDeleteView.as_view(), name='employee-delete'),

    path('renovate/<str:local>/<int:pk>/<int:days>', views.RenovateView.as_view(), name='renovate'),
]

apps/sales/urls.py
# Django
from django.urls import path
# Apps
from . import views

app_name = "sales_app"

urlpatterns = [
    path('ventas/<str:local>/<int:month>/<int:year>', views.MonthSale.as_view(), name='resumen_sales'),
    path('ventas/<str:local>/<int:day>/<int:month>/<int:year>', views.DaySale.as_view(), name='day_sales'),

    path('administrador/ventas/', views.PanelSu.as_view(), name='panel_su'),
    path(
        'administrador/ventas/<str:local>/<int:month>/<int:year>',
        views.MonthSaleSu.as_view(),
        name='r_sales_su'
    ),
    path(
        'administrador/bloquear_mes/<str:local>/<int:month>/<int:year>',
        views.LockMonthSu.as_view(),
        name='lock_month_su'
    ),
    path(
        'administrador/desbloquear_mes/<str:local>/<int:month>/<int:year>',
        views.UnlockMonthSu.as_view(),
        name='unlock_month_su'
    ),
    path(
        'administrador/desbloquear_mes/<str:local>/<int:month>/<int:year>',
        views.GenerateExcel.as_view(),
        name='unlock_month_su'
    ),
    path(
        'administrador/generar-excel/<str:local>/<int:month>/<int:year>',
        views.GenerateExcel.as_view(),
        name='generate_excel'
    ),
    path(
        'administrador/change-date',
        views.ChangeDate.as_view(),
        name='change_date'
    ),
]

apps/users/urls.py
# Django
from django.urls import path
# Apps
from . import views

app_name = "users_app"

urlpatterns = [
    path('login', views.LoginUser.as_view(), name='user-login'),
    path('logout', views.LogoutView.as_view(), name='user-logout'),
    path('panel', views.PanelView.as_view(), name='panel'),
]

personal/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    # users app
    re_path('', include('apps.users.urls')),
    re_path('', include('apps.locals.urls')),
    re_path('', include('apps.sales.urls')),
    re_path(r'^kuai/(.*)$', TemplateView.as_view(template_name='index.html')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/users/models.py
# Django
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from django.db import models
from django.utils.safestring import mark_safe

# Apps
from apps.users.managers import UserManager
from apps.locals.models import Local

# Other
import qrcode
from PIL import Image, ImageDraw
from io import BytesIO
from django.core.files import File


class User(AbstractBaseUser, PermissionsMixin):

    TYPE_USER = [
        ('1', 'Dueño'),
        ('2', 'Gerente'),
        ('3', 'Staff'),
    ]

    dni = models.IntegerField(unique=True)
    email = models.EmailField(blank=True, null=True)
    type_user = models.CharField("Tipo de Usuario", max_length=1, choices=TYPE_USER, default='3')
    first_name = models.CharField('Nombres', max_length=100)
    last_name = models.CharField('Apellidos', max_length=100)
    phone = models.CharField('Telefono', max_length=100, help_text="809-472-2626", blank=True, null=True)
    image = models.ImageField('foto', upload_to='media/user/employees', blank=True, null=True)
    qr = models.ImageField(upload_to='media/user/qrcode', blank=True)

    #
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)

    USERNAME_FIELD = 'dni'

    REQUIRED_FIELDS = [
        'first_name', 'last_name', 'type_user'
    ]

    objects = UserManager()

    class Meta:
        verbose_name = 'Usuario'
        verbose_name_plural = 'Usuarios'

    def get_short_name(self):
        return self.first_name

    def get_full_name(self):
        return "{} {}".format(self.first_name, self.last_name)

    def qr_thumbnail(self):
        if self.qr:
            return mark_safe('<img src="/%s" width="140" />' % self.qr)
        return '-'

    def locals(self):
        if self.is_superuser:
            return Local.objects.all()
        else:
            if self.type_user == '1':
                return Local.objects.filter(owner=self)
            elif self.type_user == '2':
                return Local.objects.filter(manager__manager=self)

    qr_thumbnail.short_description = 'Qr'
    qr_thumbnail.allow_tags = True

    def __str__(self):
        return self.get_full_name()

    def save(self, *args, **kwargs):
        # url = 'http://personal.devotoshopping.com.ar/dni/{}'.format(self.dni)
        url = self.dni
        qrcode_img = qrcode.make(url)
        canvas = Image.new("RGB", (300, 300), "white")
        ImageDraw.Draw(canvas)
        canvas.paste(qrcode_img)
        buffer = BytesIO()
        canvas.save(buffer, "PNG")
        self.qr.save('qr.png', File(buffer), save=False)
        canvas.close()
        return super(User, self).save(*args, **kwargs)

apps/users/forms.py
from django import forms
from django.contrib.auth import authenticate
# Apps
# from .models import User


class LoginForm(forms.Form):
    dni = forms.CharField(
        label='E-mail',
        required=True,
        widget=forms.NumberInput(
            attrs={
                'id': 'form1Example1',
                'class': 'form-control',
            }
        )
    )
    password = forms.CharField(
        label='Contraseña',
        required=True,
        widget=forms.PasswordInput(
            attrs={
                'id': 'form1Example2',
                'class': 'form-control',
            }
        )
    )

    def clean(self):
        dni = self.cleaned_data['dni']
        password = self.cleaned_data['password']

        if not authenticate(dni=dni, password=password):
            raise forms.ValidationError(
                'Los datos de usuario no son correctos'
            )

        return self.cleaned_data

apps/users/views.py
# Django
# from ast import Try
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect
from django.views.generic.edit import (
    FormView
)
from django.contrib.auth.mixins import LoginRequiredMixin
# from django.shortcuts import render
from django.views.generic import (View)

# Apps
# from apps.users.models import User
from apps.locals.models import Local
from .forms import (
    LoginForm,
)
import datetime


class LoginUser(FormView):
    template_name = 'users/login.html'
    form_class = LoginForm

    def get_success_url(self):
        if self.request.user.is_superuser:
            return reverse_lazy('sales_app:panel_su')
        else:
            # if self.request.user.type_user == '1':
            #     ls = Local.objects.filter(owner=self.request.user)
            # elif self.request.user.type_user == '2':
            #     ls = Local.objects.filter(manager__manager=self.request.user)
            return reverse_lazy('users_app:panel')

    def form_valid(self, form):
        user = authenticate(
            dni=form.cleaned_data['dni'],
            password=form.cleaned_data['password']
        )
        login(self.request, user)
        return super(LoginUser, self).form_valid(form)


class LogoutView(View):
    def get(self, request, *args, **kargs):
        logout(request)
        return HttpResponseRedirect(
            reverse(
                'users_app:user-login'
            )
        )


class PanelView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        if self.request.user.type_user == '1':
            ls = Local.objects.filter(owner=request.user)
        elif request.user.type_user == '2':
            ls = Local.objects.filter(manager__manager=request.user)

        return render(request, 'users/panel.html', {
            'locals': ls,
            'today': datetime.datetime.today()
        })

templates/users/entry.html
{% load  static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta http-equiv="x-ua-compatible" content="ie=edge" />
    <title>{% block title %}{% endblock title %}</title>
    <!-- MDB icon -->
    <link rel="icon" href="img/mdb-favicon.ico" type="image/x-icon" />
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"/>
    <!-- Google Fonts Roboto -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700;900&display=swap"/>
    <!-- MDB -->
    <link rel="stylesheet" href="{% static "css/mdb.min.css" %}" />
  </head>
  <body>
    <!--Main Navigation-->
    <header>
      <style>
        #intro {
          background-image: url(https://devotoshopping.neexcdn.com.ar/wp-content/uploads/2015/11/Background-Home.jpg);
          height: 100vh;
          overflow: auto;
        }
        .mask {
          overflow: auto;
        }
        .card {
          max-width: 300px;
          margin: 100px auto 0;
          background-color: #42515a;
          box-shadow: 0 10px 90px #00000024;
          text-align: center;
          font-size: 20px;
          border-radius: 15px;
          color: #fff;
          margin-bottom: 15px;
        }
        .card .card-header {
          position: relative;
          height: 48px;
          margin-bottom: .8rem;
        }
        .card .card-header .profile-img {
          width: 130px;
          height: 130px;
          border-radius: 1000px;
          position: absolute;
          left: 50%;
          transform: translate(-50%, -50%);
          box-shadow: 0 0 20px #00000033;
          background: #fff;
        }
        .card .card-header.vencido .profile-img {
          border: 8px solid rgba(249,49,84,1)!important;
        }
        .card .card-header.activo .profile-img {
          border: 8px solid rgba(0,183,74,1)!important;
        }
        .card .card-body {
          padding: 35px 40px;
          font-size: 16px;
        }
        .card .card-body .name {
          margin-top: 5px;
          font-size: 22px;
          font-weight: bold;
        }
        .card .card-body .mail {
          color: #c2bdbd;
        }
        .card .card-body .job {
          margin-top: 10px;
        }
        .card .card-body .job a{
          color: #fff;
        }
        .card .social-links {
          display: flex;
          justify-content: center;
          align-items: center;
          margin-top: 5px;
          flex-direction: column;
        }
        .card .card-footer {
          border-bottom-left-radius: 15px;
          border-bottom-right-radius: 15px;
          padding: 20px 0 20px 0;
        }
        .card .card-footer.vencido {
          background-color: rgba(249,49,84,1)!important;
        }
        .card .card-footer.activo {
          background-color: rgba(0,183,74,1)!important;
        }
        .card .card-footer .count {
          font-size: 14px;
        }
        .input-group>.form-control {
          min-height: calc(2.08rem + 3px);
          height: calc(2.08rem + 3px);
        }
        .search-items {
          color: #fff;
        }
        .img-logo {
          width: 25%;
        }
        @media screen and (max-width: 575px) {
          .card {
            width: 96%;
          }

          .card .card-body {
            padding: 20px;
          }
          .card-header {
            margin-bottom: 1.3rem;
          }
        }
        @media screen and (max-width: 768px) {
          .img-logo {
            width: 50%;
          }
        }
      </style>
      <!-- Background image -->
      <div id="intro" class="bg-image shadow-2-strong">
        <div class="mask h-100" style="background-color: rgba(0, 0, 0, 0.5);">
          <div class="container">
            <div class="text-center mt-3 mb-3">
              <img class="img-logo" src="{% static 'images/Devoto Logo-05.png' %}" alt="devoto">
            </div>
            <div class="row justify-content-center">
              <div class="col-md-7">
                <form method="GET">
                  <div id="custom-search-input">
                    <div class="input-group col-md-12">
                      <input type="text" class="form-control" placeholder="Buscar..." name="search">
                      <span class="input-group-list">
                        <button type="submit" class="btn btn-success">Buscar</button>
                      </span>
                    </div>
                  </div>
                </form>
              </div>
              <div class="col-md-7">
                {% if user_search %}
                  <div class="card">
                    <div class="card-header {% if valid %}activo{% else %}vencido{% endif %}">
                      {% if user_search.image %}
                        <img src="{{ user_search.image }}" alt="Profile Image" class="profile-img">
                      {% else %}
                        <img src="{% static 'images/user.png' %}" alt="Profile Image" class="profile-img">
                      {% endif %}
                    </div>
                    <div class="card-body">
                      <div>
                        <img src="{{ user_search.qr }}" alt="qr" style='width: 50%;'>
                      </div>
                      <p class="name mb-0">{{ user_search }}</p>
                      <p class="mb-0">{{ user_search.get_type_user_display }}</p>
                      <p class="mb-0">{{ user_search.dni }}</p>
              
                      {% if user_search.phone %}
                        <p class="job mb-0"><a href="tel:{{ user.phone }}">{{ user_search.phone }}</a></p>
                      {% else %}
                        <p class="mb-0">No posee teléfono registrado</p>
                      {% endif %}
              
                      <div class="social-links">
                        <span class="name mt-0">Local</span>
                        <div>
                          {% for e in user_search.employee.all %}
                            {% if e.local.logo %}
                              <img src="{{ e.local.logo }}" alt="Profile Image" class="profile-img" width='50'>
                            {% else %}
                              <li>{{ e.local.name }}</li>
                            {% endif %}
                          {% endfor %}
                        </div>
                      </div>
                    </div>
                    <div class="card-footer {% if valid %}activo{% else %}vencido{% endif %}">
                      {% if valid %}
                        <p class="count mb-0">Activo</p>
                      {% else %}
                        <p class="count mb-0">Vencido</p>
                      {% endif %}
                    </div>
                  </div>
                {% else %}
                  <p class="search-items">No hay coincidencias</p>
                {% endif %}
              </div>
            </div>
          </div>
        </div>
      </div>
      <!-- Background image -->
    </header>
    <!--Main Navigation-->

    <!--Footer-->
    <!-- MDB -->
    <script type="text/javascript" src=" {% static "js/mdb.min.js" %}"></script>
  </body>
</html>

templates/users/login.html
{% load  static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta http-equiv="x-ua-compatible" content="ie=edge" />
    <title>{% block title %}{% endblock title %}</title>
    <!-- MDB icon -->
    <link rel="icon" href="img/mdb-favicon.ico" type="image/x-icon" />
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"/>
    <!-- Google Fonts Roboto -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700;900&display=swap"/>
    <!-- MDB -->
    <link rel="stylesheet" href="{% static "css/mdb.min.css" %}" />
  </head>
  <body>
    <!--Main Navigation-->
    <header>
      <style>
        #intro {
          background-image: url(https://devotoshopping.neexcdn.com.ar/wp-content/uploads/2015/11/Background-Home.jpg);
          height: 100vh;
        }
        .navbar .nav-link {
          color: #fff !important;
        }
        .text-error {
          font-size: .8rem;
          color: red;
        }
      </style>
      <!-- Background image -->
      <div id="intro" class="bg-image shadow-2-strong">
        <div class="mask d-flex align-items-center h-100" style="background-color: rgba(0, 0, 0, 0.5);">
          <div class="container">
            <div class="text-center mb-5">
              <img src="{% static 'images/Devoto Logo-05.png' %}" alt="devoto">
            </div>
            <div class="row justify-content-center">
              <div class="col-xl-5 col-md-8">
                <form method="POST" class="bg-white  rounded-5 shadow-5-strong p-5">
                  {% csrf_token %}
                  <!-- Email input -->
                  <div class="form-outline mb-4">
                    {{ form.dni }}
                    <label class="form-label" for="form1Example1">NÚMERO DE LOCAL</label>
                  </div>
                  {% for x in form.dni.errors %}
                    <p class="text-errors">* {{x}}</p>
                  {% endfor %}
                  <!-- Password input -->
                  <div class="form-outline mb-4">
                    {{ form.password }}
                    <label class="form-label" for="form1Example2">Contraseña</label>
                  </div>
                  {% if form.errors %}
                    <p class="text-error">* Los datos suministrados no son correctos</p>
                  {% endif %}
                  <!-- Submit button -->
                  <button type="submit" class="btn btn-primary btn-block">Iniciar Sesion</button>
                </form>

              </div>
            </div>
          </div>
        </div>
      </div>

      <!-- Background image -->
    </header>
    <!--Main Navigation-->

    <!--Footer-->
    <!-- MDB -->
    <script type="text/javascript" src=" {% static "js/mdb.min.js" %}"></script>
  </body>
</html>

templates/users/panel.html
{% extends "layout.html" %}

{% load static %}

{% block css %}
{% endblock css %}

{% block content %}
  <div class="px-4 sm:px-6 lg:px-8">
    <div class="mt-8 flex flex-col">
      <div class="-my-2 -mx-4 overflow-x-auto sm:-mx-6 lg:-mx-8">
        <div class="inline-block min-w-full py-2 align-middle md:px-6 lg:px-8">
          <div class="overflow-hidden shadow ring-1 ring-black ring-opacity-5 md:rounded-lg">
            <table class="min-w-full divide-y divide-gray-300">
              <thead class="bg-gray-50">
                <tr>
                  <th scope="col" class="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-6">Local</th>
                  <!-- <th scope="col" class="relative py-3.5 pl-3 pr-4 sm:pr-6"> -->
                    <span class="sr-only">Edit</span>
                  </th>
                  {% if user.type_user == '1' %}
                    <th scope="col" class="relative py-3.5 pl-3 pr-4 sm:pr-6">
                      <span class="sr-only">Edit</span>
                    </th>
                  {% endif %}
                </tr>
              </thead>
              <tbody class="divide-y divide-gray-200 bg-white">
                {% for l in locals %}
                  <tr>
                    <td class="whitespace-nowrap py-4 pl-4 pr-3 text-sm font-medium text-gray-900 sm:pl-6">{{ l }}</td>
                    <!-- <td class="relative whitespace-nowrap py-4 pl-3 pr-4 text-right text-sm font-medium sm:pr-6">
                      <a href="{% url 'locals_app:panel' l.slug %}" class="text-indigo-600 hover:text-indigo-900">Personal</a>
                    </td> -->
                    {% if user.type_user == '1' %}
                      <td class="relative whitespace-nowrap py-4 pl-3 pr-4 text-right text-sm font-medium sm:pr-6">
                        <a href="{% url 'sales_app:resumen_sales' l.slug today.month today.year %}" class="text-indigo-600 hover:text-indigo-900">Ventas</a>
                      </td>
                    {% endif %}
                  </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

{% block js %}
{% endblock js %}